defmodule MPP.Session.ChannelTest do
  use ExUnit.Case, async: true

  alias MPP.Session.Channel

  @payer "0x1111111111111111111111111111111111111111"
  @recipient "0x2222222222222222222222222222222222222222"
  @token "0x3333333333333333333333333333333333333333"
  @salt "0x0000000000000000000000000000000000000000000000000000000000000001"
  @authorized_signer "0x4444444444444444444444444444444444444444"
  @escrow_contract "0x5555555555555555555555555555555555555555"
  @chain_id 42_431

  # Generated by executing refs/mppx/src/tempo/legacy/session/Channel.ts's
  # AbiParameters.encode + Hash.keccak256 path with the fields above.
  @mppx_channel_id "0x5db832ef1f06a767e0561f2fe53231240f8804895a21d5804ddb15b329c73c5e"

  describe "compute_id/1" do
    test "matches the mppx Channel.ts vector" do
      assert {:ok, @mppx_channel_id} = Channel.compute_id(id_params())
      assert Channel.compute_id!(Map.to_list(id_params())) == @mppx_channel_id
    end

    test "binds every channel identity input" do
      replacements = %{
        payer: "0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        payee: "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        token: "0xcccccccccccccccccccccccccccccccccccccccc",
        salt: "0x0000000000000000000000000000000000000000000000000000000000000002",
        authorized_signer: "0xdddddddddddddddddddddddddddddddddddddddd",
        escrow_contract: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        chain_id: 1
      }

      for {field, replacement} <- replacements do
        assert {:ok, changed_id} = Channel.compute_id(Map.put(id_params(), field, replacement))
        refute changed_id == @mppx_channel_id
      end
    end

    test "rejects malformed identity fields" do
      assert {:error, {:invalid_address, :payer}} =
               Channel.compute_id(Map.put(id_params(), :payer, "0xdead"))

      assert {:error, :invalid_salt} =
               Channel.compute_id(Map.put(id_params(), :salt, "0x01"))

      assert {:error, :invalid_chain_id} =
               Channel.compute_id(Map.put(id_params(), :chain_id, -1))

      assert {:error, :invalid_channel_id_parameters} = Channel.compute_id(%{})
      assert {:error, {:invalid_channel_id, nil}} = Channel.normalize_id(nil)

      assert_raise ArgumentError, fn ->
        Channel.compute_id!(Map.put(id_params(), :chain_id, -1))
      end
    end
  end

  describe "channel lifecycle" do
    test "transitions open to active to closed" do
      assert {:ok, open} = Channel.new(channel_opts())
      assert open.status == :open
      assert open.cumulative_amount == 0

      assert {:ok, active} = Channel.activate(open)
      assert active.status == :active

      assert {:ok, closed} = Channel.close(active)
      assert closed.status == :closed
    end

    test "rejects invalid transitions" do
      open = Channel.new!(channel_opts())

      assert {:error, {:invalid_transition, :open, :closed}} = Channel.close(open)
      assert {:ok, active} = Channel.activate(open)
      assert {:error, {:invalid_transition, :active, :active}} = Channel.activate(active)
      assert {:ok, closed} = Channel.close(active)
      assert {:error, {:invalid_transition, :closed, :closed}} = Channel.close(closed)
    end

    test "validates channel state amounts and identifiers" do
      assert {:error, {:invalid_channel_id, "0xdead"}} =
               Channel.new(Keyword.put(channel_opts(), :channel_id, "0xdead"))

      assert {:error, {:invalid_amount, :deposit}} =
               Channel.new(Keyword.put(channel_opts(), :deposit, -1))

      assert {:error, {:invalid_amount, :cumulative_amount}} =
               Channel.new(Keyword.put(channel_opts(), :cumulative_amount, "1"))

      assert {:error, :cumulative_amount_exceeds_deposit} =
               Channel.new(Keyword.merge(channel_opts(), deposit: 1, cumulative_amount: 2))

      assert_raise ArgumentError, fn ->
        Channel.new!(Keyword.put(channel_opts(), :payer, "invalid"))
      end
    end
  end

  describe "action wire values" do
    test "uses camelCase only at the JSON boundary" do
      mappings = [open: "open", top_up: "topUp", voucher: "voucher", close: "close"]

      for {action, wire_value} <- mappings do
        assert Channel.action_to_wire(action) == wire_value
        assert Channel.action_from_wire(wire_value) == {:ok, action}
      end

      assert {:error, :invalid_action} = Channel.action_from_wire("top_up")
      assert {:error, :invalid_action} = Channel.action_from_wire(:top_up)
    end
  end

  defp id_params do
    %{
      payer: @payer,
      payee: @recipient,
      token: @token,
      salt: @salt,
      authorized_signer: @authorized_signer,
      escrow_contract: @escrow_contract,
      chain_id: @chain_id
    }
  end

  defp channel_opts do
    [
      channel_id: @mppx_channel_id,
      payer: @payer,
      recipient: @recipient,
      token: @token,
      deposit: 1_000_000
    ]
  end
end
